### ISSUE TITLE
有点疑问

### ISSUE THREAD

**Issue by DSPerson** [cc1104666/HanaNetwotk#1]
交易成功hash 也显示成功了 但是Hana官网里面  Grows 一直显示0 ，neng能帮忙看一下吗
<img width="745" alt="image" src="https://github.com/user-attachments/assets/47854184-0f06-4127-a026-dc700f7888f7">

**Comment by cc1104666** [comment]
这个没问题呀，现在官方出了一键兑换所有grows分，所以会把grows全部用完去兑换成分

**Comment by DSPerson** [comment]
> 这个没问题呀，现在官方出了一键兑换所有grows分，所以会把grows全部用完去兑换成分

但是这个质押数量一致是0啊 我用你的脚本交易了

<img width="264" alt="image" src="https://github.com/user-attachments/assets/398049e9-c3fa-4725-8ec6-deb2ff7446bc">
